server:
  port: 8082

spring:
  application:
   name: ManagementService

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.use.type.headers: false
        spring.json.value.default.type: com.cor.managementservice.dto.RequestToDataBase
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: "*"
      group-id: b-group

  datasource:
    url: jdbc:postgresql://localhost:5432/manager
    username: root
    password: root

  jpa:
    show-sql: true
    properties:
      hibernate.hibernate.format_sql: true
      hibernate:
        jdbc:
          batch_size: 50
        order-inserts: true
        order-updates: true
        batch-versioned-data: true
    hibernate:
      ddl-auto: none


  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yml
    drop-first: false

joke:
  backup-file: D:/BD/reserve.json

kafka:
  topic:
    request: to-database-event
    response: from-database-event